
###
### ----------- EVENT TESTING -----------
###
### FULLY WORKING

POST http://localhost:8000/restapi/events/
Content-Type: application/json

{
  "club": 4,
  "title": "Spring Festival",
  "description": "A festival to celebrate the arrival of spring.",
  "start_time": "2025-04-20T10:00:00Z",
  "end_time": "2025-04-20T18:00:00Z",
  "location": "Central Park",
  "capacity": 200
}

###

POST http://localhost:8000/restapi/events/
Content-Type: application/json

{
  "club": 1,
  "title": "Spring Festival 2",
  "description": "A festival to celebrate the arrival of spring. 2",
  "start_time": "2025-04-20T10:00:00Z",
  "end_time": "2025-04-20T18:00:00Z",
  "location": "Central Park 2",
  "capacity": 202
}

###

GET http://localhost:8000/restapi/events/

###

### PUT WORKING

PATCH http://localhost:8000/restapi/events/1/
Content-Type: application/json

{
  "title": "Updated Spring Festival",
  "description": "A festival to celebrate the arrival of spring.",
  "start_time": "2025-04-20T10:00:00Z",
  "end_time": "2025-04-20T18:00:00Z",
  "location": "Updated Central Park",
  "capacity": 200
}

###

DELETE http://localhost:8000/restapi/events/3/

###








###
### ----------- CLUB TESTING -----------
###
### Use PATCH for updates
### FULLY WORKING

POST http://localhost:8000/restapi/clubs/
Content-Type: application/json

{
    "user": {
        "email": "owner8@example.com",
        "password": "securepassword"
    },
    "club_name": "Awesome Club 8",
    "description": "A description for Awesome Club.",
    "social_media_handles": {"twitter": "@awesomeclubtw", "instagram": "@awesomeclubinsta"}
}

###

POST http://localhost:8000/restapi/clubs/
Content-Type: application/json

{
    "user": {
      "email": "owner2@example.com",
      "password": "securepassword"
    },
    "club_name": "Some Club",
    "description": "A description for Awesome Club.",
    "social_media_handles": {
      "twitter": "@awesomeclubtw",
      "instagram": "@awesomeclubinsta"
    }
  }

###

GET http://localhost:8000/restapi/clubs/

###

GET http://localhost:8000/restapi/clubs/2/

### Use Patch for partial updates --> PUT requires all fields (creates issues with unique=True fields)

PATCH http://localhost:8000/restapi/clubs/1/
Content-Type: application/json

{
  "user": {
    "email": "owner@example.com",
    "first_name": "Club",
    "last_name": "Owner",
    "password": "updatedsecurepassword"
  },
  "name": "Awesome Club Updated",
  "description": "Updated description for Awesome Club.",
  "social_media_handles": {"twitter": "@awesomeclubtw", "instagram": "@awesomeclubinsta"}
}

###

DELETE http://localhost:8000/restapi/clubs/1/

###

PATCH http://localhost:8000/restapi/clubs/slug/cool-club/
Content-Type: application/json

{
  "slug": "cool-club",
  "club_name": "Cool Club",
  "description": "some updated description",
  "social_media_handles": null,
  "spirit_rating": 1,
  "followers_count": 0,
  "events_count": 0
}

###

PATCH http://localhost:8000/restapi/clubs/slug/cool-club/
Content-Type: application/json

{
    "club_name": "Cool Club",
    "description": "some updated description",
    "social_media_handles": {"twitter": "@awesomeclubtw", "instagram": "@awesomeclubinsta"}
}

###

GET http://localhost:8000/restapi/clubs/slug/cool-club/





###
### ----------- STUDENT TESTING -----------
###
### Use PATCH for updates
### FULLY WORKING

POST http://localhost:8000/restapi/students/
Content-Type: application/json

{
  "user": {
    "email": "student1@example.com",
    "password": "securepassword"
  },
  "first_name": "John",
  "last_name": "Doe",
  "major": "Computer Science",
  "graduation_year": 2025
}

###

POST http://localhost:8000/restapi/students/
Content-Type: application/json

{
  "user": {
    "email": "student2@example.com",
    "first_name": "Jane",
    "last_name": "Smith",
    "password": "securepassword2"
  },
  "major": "Mathematics",
  "graduation_year": 2024
}

###

GET http://localhost:8000/restapi/students/

###

GET http://localhost:8000/restapi/students/1/

### Use Patch for partial updates --> PUT requires all fields (creates issues with unique=True fields)

PUT http://localhost:8000/restapi/students/1/
Content-Type: application/json

{
  "user": {
    "email": "student1@example.com",
    "first_name": "John",
    "last_name": "Doe",
    "password": "securepassword"
  },
  "major": "Updated Software Engineering",
  "graduation_year": 2025
}

###

DELETE http://localhost:8000/restapi/students/2/

###



















### TESTING ROUTES - AFTER BUG CHANGES

GET http://localhost:8000/restapi/clubs/
###
GET http://localhost:8000/restapi/clubs/4/
###
PATCH http://localhost:8000/restapi/clubs/4/
Content-Type: application/json

{
  "club_name": "Cool Club",
  "description": "some description updated",
  "social_media_handles": {
    "twitter": "@awesomeclubtw",
    "instagram": "@awesomeclubinsta"
  }
}
###
PATCH http://localhost:8000/restapi/clubs/slug/your-club/
Content-Type: application/json

{
  "club_name": "Your Club",
  "description": "some",
  "social_media_handles": {
    "twitter": "@sometw"
  }
}
###
POST http://localhost:8000/restapi/clubs/
Content-Type: application/json

{
  "user": {
    "email": "owner3@example.com",
    "password": "securepassword"
  },
  "club_name": "Some Club 2",
  "description": "A description for Awesome Club.",
  "social_media_handles": {
    "twitter": "@awesomeclubtw",
    "instagram": "@awesomeclubinsta"
  }
}
###
DELETE http://localhost:8000/restapi/clubs/6/
###
DELETE http://localhost:8000/restapi/clubs/slug/some-club-2/


###

GET http://localhost:8000/restapi/students/






###

GET http://localhost:8000/restapi/events/


